server:
  port: 2028
spring:
  application:
    name: gateway-service
  cloud:
    zookeeper:
      connect-string: 147.182.180.167:22181
      discovery:
        enabled: true
        instanceId: ${spring.application.name}:${random.value}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://147.182.180.167:28080/realms/master
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: roadmap
            client-secret: MEAlgrg0R2QLRAR8vLJPXzXaoWkuj5Fa
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: http://localhost:2028/login/oauth2/code/keycloak
            client-authentication-method: client_secret_basic
        provider:
          keycloak:
            issuer-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.jwk-set-uri}
            user-name-attribute: preferred_username